### ISSUE TITLE
Don't use deprecated "debootstrap" Ubuntu images

### ISSUE THREAD

**Issue by iSDP** [beevelop/docker-java#1]
The right image for Ubuntu is ubuntu:wily :)

**Comment by beevelop** [comment]
I'm on it. I plan to base my whole image hierarchy on the fresh Xenial ('cause LTS 🚀 ).

I might need some time to test all images with the new base image, so feedback is appreciated. Before upgrading `latest` you will be able to check it out on the `xenial` branch.

**Comment by iSDP** [comment]
Wait with Xenial until 16.04.1 is out, until then, using ubuntu:wily will suffice

**Comment by beevelop** [comment]
Just precautionar? Or does the current version have some major implications?

**Comment by iSDP** [comment]
Not everything is ready to run on 16.04, and there are bugs that still need solving :)

It's kind of a best practice to wait for a x.1 release when using LTS
